<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mbsa" nsURI="http://cam.ac.uk/mbsa/mbsa" nsPrefix="mbsa_">
  <eClassifiers xsi:type="ecore:EClass" name="MBSAPackage" eSuperTypes="http://cam.ac.uk/mbsa/base#//ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mbsaPackages" upperBound="-1"
        eType="#//MBSAPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentPackage" upperBound="-1"
        eType="ecore:EClass http://cam.ac.uk/mbsa/component#//ComponentPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementPackage" upperBound="-1"
        eType="ecore:EClass http://cam.ac.uk/mbsa/requirement#//RequirementPackage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazardPackage" upperBound="-1"
        eType="ecore:EClass http://cam.ac.uk/mbsa/hazard#//HazardPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="safetyConceptPackage" upperBound="-1"
        eType="ecore:EClass http://cam.ac.uk/mbsa/safety_concept#//SafetyConceptPackage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ftaPackage" upperBound="-1"
        eType="ecore:EClass http://cam.ac.uk/mbsa/fta#//FTAPackage" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
