<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="arch" nsURI="http://automated.fmea/arch" nsPrefix="arch">
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureElement" abstract="true"
      eSuperTypes="http://automated.fmea/base#//ArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentPackage" eSuperTypes="#//ArchitectureElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ArchitectureElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentPackageInterface" eSuperTypes="#//ComponentPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceFor" eType="#//ComponentPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentPackageBinding" eSuperTypes="#//ComponentPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participantPackage" lowerBound="2"
        upperBound="2" eType="#//ComponentPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureAsset" abstract="true" eSuperTypes="#//ArchitectureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true" eSuperTypes="#//ArchitectureAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentRelationship" abstract="true"
      eSuperTypes="#//ArchitectureAsset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="#//Component"/>
  </eClassifiers>
</ecore:EPackage>
